spring:
  datasource:
    url: jdbc:mysql://localhost:3306/patientmanage
    username: root
    password: Kushan23

  jpa:
    hibernate:
      ddl-auto: update

  security:
    user:
      name: kushan
      password: 12345


